#!/bin/bash

if [[ $1 == 'clean' ]]
then
 [[ -d RPMS ]] && rm -fr RPMS/*
 [[ -d SRPMS ]] && rm -fr SRPMS/*
 echo "Cleaned RPMS & SRPMS"
 exit 0
fi

dist=$( rpm --showrc | grep ' dist\s' | awk '{ print $3 }' )
release=$( grep -i Release SPECS/ghost.spec | egrep -o '[0-9]+' )$dist

ver=$1

if [[ $ver == '' ]]
then 
  ver=$( curl -s -I https://ghost.org/zip/ghost-latest.zip |
    grep Location: |
    egrep -o '([0-9]+\.){2}[0-9]+' )
fi

echo "Building ghost '$ver' -> "

if [[ ! -f SOURCES/ghost-$ver.zip ]]
then
  spectool -g -d "_ver $ver" -C SOURCES SPECS/ghost.spec
fi

mock --buildsrpm -D "_ver $ver" \
  --sources SOURCES --resultdir=SRPMS/  \
  --spec SPECS/ghost.spec &&
  mock -D "_ver $ver" \
  --resultdir=RPMS/ \
  SRPMS/ghost-${ver}-${release}.src.rpm 


